---
title: "Iterations and list cols  "
author: "My An Huynh"
date: "2024-10-31"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

```

## Here's some lists 

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(1:100),
  mat = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE),
  summary = summary(rnorm(1000))
)

l[["mat"]][1, 3]
```


Make a list that's hopefully a bit more useful

```{r}
list_norm = 
  list(
    a = rnorm(20, 0, 5),
    b = rnorm(20, 4, 5),
    c = rnorm(20, 0, 10),
    d = rnorm(20, 4, 10)
  )

list_norm[["a"]]

```

Reuse the function we wrote last time. 

```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(out_df)
}
```

Let's use the function to take mean and sd of all samples

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])

```

## Use a for loop

Create output list, and run a for loop
We have 4 lists of normal (a,b,c,d). For any of those, we have an output list to catch each output separately 

```{r}
output = vector("list", length = 4)

for (i in 1:4)  {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
}

output
```


